In [1]:
# NumPy behaves differently than Python

a = [1,2,3]
b = [4,5,6]
c = a + b
c

[1, 2, 3, 4, 5, 6]

In [2]:
# Import NumPy
import numpy as np

In [3]:
# NumPy adds items
b = np.array(b)
c = a + b
c

array([5, 7, 9])

In [4]:
# Lets calculate didvidend yield
# Dividend Yield = Annual Dividend / Current Stock Price

dividends = [1, 1.5, 1.75, 0.75, 1.25]
stock_prices = [50, 55, 62, 47, 84]

In [5]:
# lets convert lists into numpy arrays
# If you use different types NumPy converts everything to string
np_dividends = np.array(dividends)
np_stock_prices = np.array(stock_prices)
np_stock_prices

array([50, 55, 62, 47, 84])

In [6]:
# now we can easy perform calculations
dividend_yield = np_dividends/np_stock_prices*100
dividend_yield

array([ 2.        ,  2.72727273,  2.82258065,  1.59574468,  1.48809524])

In [7]:
dividend_yield[1]

2.7272727272727271

In [8]:
# values greater than 2.72
dividend_yield > 2.72

array([False,  True,  True, False, False], dtype=bool)

In [9]:
# or you could get the actual values
dividend_yield[dividend_yield > 2.72]

array([ 2.72727273,  2.82258065])

In [10]:
# 2D NumPy Arrays
# ndarray stands for N-dimensional array
type(np_dividends)

numpy.ndarray

In [11]:
# we can create 2d array from a regular python list of lists
np_2d = np.array([[1, 1.5, 1.75, 0.75, 1.25],[50, 55, 62, 47, 84]])
np_2d

array([[  1.  ,   1.5 ,   1.75,   0.75,   1.25],
       [ 50.  ,  55.  ,  62.  ,  47.  ,  84.  ]])

In [12]:
# we got rectangular data structure
# lets see how many rows and colums using shape
np_2d.shape

(2, 5)

In [13]:
# Can get number of columns by [row]
np_2d.shape[1]

5

In [14]:
# By selecting the 0th column in particular, you getting number of rows
np_2d[:,0].shape

(2,)

In [22]:
# You can ask for "all the columns up to but not including 4"
np_2d[:,2:4].shape

(2, 2)

In [23]:
# with a 2d array we can do indexing 
np_2d[1]

array([ 50.,  55.,  62.,  47.,  84.])

In [24]:
np_2d[1][1]

55.0

In [25]:
# or you could subsetting
# [row,column]
np_2d[1,1]

55.0

In [26]:
# or we could get entire second row
np_2d[1,:]

array([ 50.,  55.,  62.,  47.,  84.])

In [27]:
# Similarly we can use mean and median functions for the whole row 
avarage_stock_price = np.mean(np_2d[1,:])
avarage_stock_price

59.600000000000001

In [28]:
#standard diviation
sd = np.std(np_2d[1,:])
sd

13.215142829345433

In [29]:
#sum
s = np.sum(np_2d[1,:])
s

298.0

In [30]:
# generate data
# (distribution mean, standard dev., number of samples)

prices = np.round(np.random.normal(50, 0.20, 10), 2)
prices

array([ 49.67,  50.12,  50.12,  49.84,  49.94,  50.15,  50.39,  49.98,
        49.85,  50.15])

In [31]:
dividends = np.round(np.random.normal(1.25, 0.20, 10), 2)
dividends

array([ 1.13,  1.11,  1.32,  1.07,  1.34,  1.38,  1.3 ,  1.12,  1.12,  1.33])

In [32]:
# create two columns
portfolio = np.column_stack((prices, dividends))
portfolio

array([[ 49.67,   1.13],
       [ 50.12,   1.11],
       [ 50.12,   1.32],
       [ 49.84,   1.07],
       [ 49.94,   1.34],
       [ 50.15,   1.38],
       [ 50.39,   1.3 ],
       [ 49.98,   1.12],
       [ 49.85,   1.12],
       [ 50.15,   1.33]])

In [33]:
# lets check median stock price
m = np.median(portfolio[:,0])
m

50.049999999999997